apiVersion: v2
name: mistral-app
description: A Helm chart for Mistral AI internship application
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
- name: postgresql
  version: 16.7.27
  repository: https://charts.bitnami.com/bitnami
  condition: postgresql.enabled
