backend:
  image: "rapidement/mistralai-internship-backend"
  tag: "latest"
  port: 8080
  service:
    type: ClusterIP
    port: 8080

frontend:
  image: "rapidement/mistralai-internship-frontend"
  tag: "latest"
  port: 3000
  service:
    type: ClusterIP
    port: 3000
  env:
    apiUrl: "http://{{ .Values.ingress.host }}"

ingress:
  enabled: true
  className: "nginx"
  host: "mistral.local"
