services:
  mistral-postgres:
    image: postgres:15-alpine
    container_name: mistral-postgres
    restart: unless-stopped
    env_file:
      - ./postgres/.env
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d mistralai']
      interval: 5s
      timeout: 5s
      retries: 5

  mistral-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mistral-backend
    env_file:
      - ./backend/.env
    ports:
      - '8080:8080'
    restart: unless-stopped
    depends_on:
      mistral-postgres:
        condition: service_healthy

  mistral-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mistral-frontend
    env_file:
      - ./frontend/.env
    ports:
      - '3000:3000'
    depends_on:
      - mistral-backend
      - mistral-postgres
    restart: unless-stopped

volumes:
  postgres_data:
