apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mistralai-internship.fullname" . }}-frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "mistralai-internship.name" . }}-frontend
  template:
    metadata:
      labels:
        app: {{ include "mistralai-internship.name" . }}-frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image }}:{{ .Values.frontend.tag }}"
          ports:
            - containerPort: {{ .Values.frontend.port }}
