apiVersion: v1
kind: Secret
metadata:
  name: mistral-secrets
  labels:
    {{- include "mistral-app.labels" . | nindent 4 }}
type: Opaque
data:
  mistral-api-key: {{ .Values.secrets.mistralApiKey | b64enc }}
  nextauth-secret: {{ .Values.secrets.nextauthSecret | b64enc }}
  github-client-id: {{ .Values.secrets.githubClientId | b64enc }}
  github-client-secret: {{ .Values.secrets.githubClientSecret | b64enc }}
  postgres-password: {{ .Values.secrets.postgresPassword | b64enc }}
  database-url: {{ .Values.secrets.databaseUrl | b64enc }}