name: Backend CI/CD

on:
  push:
    branches: ['main']
    paths:
      - 'backend/**'
  pull_request:
    branches: ['main']
    paths:
      - 'backend/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build backend image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: false
          tags: backend:test

      - name: Scan backend image with Trivy
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: backend:test
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL'

  push-to-registry:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Short SHA
        id: sha
        run: echo "SHA_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push backend image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.APP_NAME }}-backend:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.APP_NAME }}-backend:${{ steps.sha.outputs.SHA_SHORT }}
